### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by deBBuu** [DmACKGL/GCPhone-Rewrite#67]
Mesagges (dispatch) works only for Police, EMS doesn't work. 
Where can I find event which create this message?

**Comment by DmACKGL** [comment]
Hey @deBBuu,

This week I had a lot of work, that's why I didn't update the resource, I hope I'll return to development next week if everything goes as planned. So sorry.

Regarding your issue, I think the resource has a problem here: https://github.com/DmACKGL/GCPhone-Rewritten/tree/master/resources/gcphone/addons/pscall check it out.

All forks and pull request fixing problems are COMPLETELY welcome (and pls do, that's the idea of having an open-source project, so everyone can help improving the resource)

**Comment by deBBuu** [comment]
I found a solution xDDD im just brainless and i started esx_ambulancejob **BEFORE** gcphone lmao

it needs to be like that:

start gcphone
start esx_policejob
start esx_ambulancejob

**Comment by DmACKGL** [comment]
Good to hear!
